# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\tgrpc_demo\"\x1e\n\x0cNumberStream\x12\x0e\n\x06number\x18\x01 \x01(\x04\"/\n\x0bTestRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07\x63ounter\x18\x02 \x01(\x05\"-\n\tTestReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07\x63ounter\x18\x02 \x01(\x05\x32\x88\x01\n\x04Test\x12=\n\x0bSendRequest\x12\x16.grpc_demo.TestRequest\x1a\x14.grpc_demo.TestReply\"\x00\x12\x41\n\x0c\x43lientStream\x12\x17.grpc_demo.NumberStream\x1a\x14.grpc_demo.TestReply\"\x00(\x01\x42\x15Z\x13grpc.test/src/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\023grpc.test/src/proto'
  _NUMBERSTREAM._serialized_start=25
  _NUMBERSTREAM._serialized_end=55
  _TESTREQUEST._serialized_start=57
  _TESTREQUEST._serialized_end=104
  _TESTREPLY._serialized_start=106
  _TESTREPLY._serialized_end=151
  _TEST._serialized_start=154
  _TEST._serialized_end=290
# @@protoc_insertion_point(module_scope)
